# GitHub Actions 工作流名称，会显示在 Actions 页面
name: Deploy to GitHub Pages

# 触发条件：定义何时运行此工作流
on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发（可自定义分支名）

# 权限设置：为工作流分配必要的权限
permissions:
  contents: write   # 写入仓库内容的权限（用于推送到gh-pages分支）

# 定义工作任务
jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用最新版本的 Ubuntu 虚拟机
    
    # 执行步骤
    steps:
      # 步骤1：检出代码
      - name: Checkout
        uses: actions/checkout@v4  # 使用官方检出动作的v4版本
      
      # 步骤2：部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # 发布当前目录的所有文件
          publish_branch: gh-pages  # 发布到 gh-pages 分支
